### ISSUE TITLE
issue with statusBar overlapping with toolBar

### ISSUE THREAD

**Issue by rnagara** [Telerik-Verified-Plugins/DocumentHandler#4]
Hello,

Is it possible to hide the `statusBar`? I'm having issue with `statusBar` overlapping with `toolBar`. Or anyway we can push `toolBar` to the bottom. I'm testing on iPhone6 Plus iOS8.3

![ray nagara-s iphone_snapshot_2015-09-02_10-59-32](https://cloud.githubusercontent.com/assets/345010/9642025/bd942758-516e-11e5-92ef-cf1435aab656.png)

I will appreciate on any suggestion.

Thank you,
Ray

**Comment by EddyVerbruggen** [comment]
Hi, perhaps you can try using the statusbar plugin to hide your app's statusbar just before you invoke the documenthandler plugin.

**Comment by rnagara** [comment]
@EddyVerbruggen, I will try that.
Thank you so much!
